// Hand-written, minimal Supabase Database type — covers only the
// columns this app actually reads/writes. Not generated by the Supabase
// CLI (`supabase gen types typescript`) because there's no live project
// to generate against yet; once one exists, prefer the generated file
// and delete this one. See README for the CLI command.

export interface LeadRow {
  id: string;
  created_at: string;
  tenant_id: string;
  source: string;
  name: string;
  phone: string;
  email: string;
  property_address: string;
  city: string | null;
  situation: string;
  timeline: string | null;
  intent_pillar: string | null;
  consent_text: string;
  consent_at: string;
  ip: string | null;
  user_agent: string | null;
  form_seconds_open: number | null;
  flagged_spam: boolean;
  owner_name: string | null;
  apn: string | null;
  est_arv: number | null;
  est_repair: number | null;
  offer_target: number | null;
  years_owned: number | null;
  score: number;
  bucket: "hot" | "warm" | "nurture";
  video_slug: string | null;
  video_url: string | null;
  status: "new" | "contacted" | "appointment" | "offer_out" | "dead" | "closed";
  utm: Record<string, unknown>;
  notes: Record<string, unknown>;
}

export type LeadInsert = Pick<
  LeadRow,
  | "tenant_id"
  | "source"
  | "name"
  | "phone"
  | "email"
  | "property_address"
  | "situation"
  | "timeline"
  | "consent_text"
  | "consent_at"
> &
  Partial<Pick<LeadRow, "ip" | "user_agent" | "form_seconds_open" | "flagged_spam" | "utm">>;

export interface OutreachLogRow {
  id: string;
  lead_id: string;
  created_at: string;
  tenant_id: string;
  channel: "call" | "text" | "email" | "video-page" | "letter" | "voicemail-drop";
  direction: "out" | "in";
  body: string | null;
  ai_generated: boolean;
  disclosed_ai: boolean;
  outcome: string | null;
}

export interface ProfileRow {
  id: string;
  tenant_id: string;
  role: "owner" | "agent";
  display_name: string | null;
}

export interface TenantRow {
  id: string;
  slug: string;
  name: string;
  config: Record<string, unknown>;
  created_at: string;
}

export interface Database {
  public: {
    Tables: {
      leads: {
        Row: LeadRow;
        Insert: LeadInsert;
        Update: Partial<LeadRow>;
        Relationships: [];
      };
      outreach_log: {
        Row: OutreachLogRow;
        Insert: Omit<OutreachLogRow, "id" | "created_at">;
        Update: Partial<OutreachLogRow>;
        Relationships: [];
      };
      profiles: {
        Row: ProfileRow;
        Insert: ProfileRow;
        Update: Partial<ProfileRow>;
        Relationships: [];
      };
      tenants: {
        Row: TenantRow;
        Insert: Partial<TenantRow>;
        Update: Partial<TenantRow>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
